version: "3"

services:
  auto-winds:
    build: .
    environment:
      REFRESH_ARTICLES: "yes"
      MONGODB_DOMAIN: "mongodb"
      # MANUSCRIPTS_JSON: "/app/config/manuscripts.json"
    ports:
      - 4010:80
    volumes:
      - ./db:/app/web/db/
      - ./config:/app/config
    networks:
      - auto-winds
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6-jammy
    expose:
      - 27017
    volumes:
      - auto-winds:/data/db
    networks:
      - auto-winds

volumes:
  auto-winds:
networks:
  auto-winds:
