version: "3"

services:
  auto-winds:
    build: .
    environment:
      - REFRESH_ARTICLES=yes
    ports:
      - 4070:80
    volumes:
      - /mnt/data/public/empire/auto-winds:/app/web
      - ./config:/app/config
