version: "3"

services:
  auto-winds:
    build: .
    environment:
      GENERATE_ARTICLES: "yes"
      # REFRESH_ARTICLES: "yes"
      MONGODB_DOMAIN: "mongodb"
    ports:
      - 127.0.0.1:4010:80
    volumes:
      - ./db:/app/web/db/
      - ./config:/app/config
    networks:
      - auto-winds
    depends_on:
      - mongodb
    tty: true

  mongodb:
    image: mongo:6-jammy
    # ports:
    #   - 127.0.0.1:28934:27017
    expose:
      - 27017
    volumes:
      - auto-winds:/data/db
    networks:
      - auto-winds

volumes:
  auto-winds:
networks:
  auto-winds:
