version: "3"

services:
  auto-winds:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - REFRESH_ARTICLES="yes"
      - MONGODB_URL="http://autowinds:27017"
    tty: true
    ports:
      - 4070:80
    volumes:
      - /www/winds.empirelrpmap.com:/app/web
      - ./config:/app/config
    networks:
      - autowinds

  mongodb:
    image: mongo:6-jammy
    expose:
      - 27017
    volumes:
      - autowinds:/data/db
    networks:
      - autowinds
volumes:
  autowinds:
networks:
  autowinds: